######################## Filebeat Configuration ############################
# This file is a full configuration example documenting all non-deprecated
# options in comments. For a shorter configuration example, that contains only
# the most common options, please see filebeat.yml in the same directory.
#
# You can find the full configuration reference here:
# https://www.elastic.co/guide/en/beats/filebeat/index.html

#================================ General ======================================
name: foobar-shipper
path:
  data: /data/filebeat/foobar
  logs: /data/filebeat/foobar/logs

filebeat.registry_file: ${path.data}/registry

#=========================== Filebeat prospectors =============================
filebeat.prospectors: 
  - type: log
    enabled: true
    paths:
        - "/home/work/log/foobar/sites/*/access.log"
    exclude_files: [".gz$"]
    close_renamed: true
    tags: ngx_access
  
  - type: log
    enabled: true
    paths:
        - "/home/work/log/foobar/ngx_error.log"
        - "/home/work/log/foobar/sites/*/error.log"
    exclude_files: [".gz$"]
    close_renamed: true
    multiline:
        pattern: '^20\d{2}/\d{2}/\d{2}\s+\d{2}:\d{2}:\d{2}'  # OpenResty
        negate: true
        match: after
    tags: ngx_error
  
  - type: log
    enabled: true
    paths:
        - '/home/work/log/foobar/waf.log'
    exclude_files: [".gz$"]
    close_renamed: true
    tags: waf


#=================================== Outputs ==================================
#------------------------------- Redis output ----------------------------------
output.redis:
  # Boolean flag to enable or disable the output module.
  enabled: false

  # The list of Redis servers to connect to. If load balancing is enabled, the
  # events are distributed to the servers in the list. If one server becomes
  # unreachable, the events are distributed to the reachable servers only.
  hosts: ["127.0.0.1:6379"]

  # The name of the Redis list or channel the events are published to. The
  # default is filebeat.
  key: foobar

  # The password to authenticate with. The default is no authentication.
  password: passwd

  # The Redis database number where the events are published. The default is 0.
  db: 0

  # The Redis data type to use for publishing events. If the data type is list,
  # the Redis RPUSH command is used. If the data type is channel, the Redis
  # PUBLISH command is used. The default value is list.
  datatype: list

  # The number of workers to use for each host configured to publish events to
  # Redis. Use this setting along with the loadbalance option. For example, if
  # you have 2 hosts and 3 workers, in total 6 workers are started (3 for each
  # host).
  #worker: 1

  # If set to true and multiple hosts or workers are configured, the output
  # plugin load balances published events onto all Redis hosts. If set to false,
  # the output plugin sends all events to only one host (determined at random)
  # and will switch to another host if the currently selected one becomes
  # unreachable. The default value is true.
  #loadbalance: true

  # The Redis connection timeout in seconds. The default is 5 seconds.
  #timeout: 5s

  # The number of times to retry publishing an event after a publishing failure.
  # After the specified number of retries, the events are typically dropped.
  # Some Beats, such as Filebeat, ignore the max_retries setting and retry until
  # all events are published. Set max_retries to a value less than 0 to retry
  # until all events are published. The default is 3.
  #max_retries: 3

  # The maximum number of events to bulk in a single Redis request or pipeline.
  # The default is 2048.
  #bulk_max_size: 2048

#----------------------------- Console output ---------------------------------
output.console:
  # Boolean flag to enable or disable the output module.
  enabled: true

  # Pretty print json event
  pretty: false


#================================ HTTP Endpoint ======================================
# Each beat can expose internal metrics through a HTTP endpoint. For security
# reasons the endpoint is disabled by default. This feature is currently experimental.
# Stats can be access through http://localhost:5066/stats . For pretty JSON output
# append ?pretty to the URL.

# Defines if the HTTP endpoint is enabled.
http.enabled: false

# The HTTP endpoint will bind to this hostname or IP address. It is recommended to use only localhost.
http.host: localhost

# Port on which the HTTP endpoint will bind. Default is 5066.
http.port: 5066